# ¿Qué tiene de diferencia los `numpy.darray`'s con las `list`?

* Arreglos NumPy son arreglas diseñados para hacer cálculos eficientemente.

* NumPy arrays guardan valores de un tipo de datos en específico.

    > Si intentamos modificar un valor de un arreglo con un valor de otro tipo de datos, obtendremos un error.

* Tienen una manera especial de acceder a sus elementos.

* Las operaciones operan diferente en los arreglos de NumPy.

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

arr.dtype

dtype('int64')

In [2]:
arr[3] = 'four'

ValueError: invalid literal for int() with base 10: 'four'

In [4]:
# Podemos especificar el dtype en el constructor del array
arr = np.array([1, 2, 3, 4, 5], dtype=np.dtype('float32'))

arr

array([1., 2., 3., 4., 5.], dtype=float32)

In [5]:
arr = np.array([1, 2, 3, 4, 5], dtype=np.dtype('str'))

arr

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [6]:
# Podemos especificar el typo como un objeto con 'O'
arr = np.array([1, 2, 3, 4, 5], dtype=np.dtype('O'))

arr

array([1, 2, 3, 4, 5], dtype=object)

In [7]:
arr[3] = 'four'
arr

array([1, 2, 3, 'four', 5], dtype=object)

> Con `dtype('O')` podemos tener arreglos con diferentes tipos de datos, sin embargo limitamos las operaciones que podemos hacer con el arreglo.

In [9]:
# Acceder a [[2, 3], [5, 6]] es diferente en una lista que en un array
list2d = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

arr2d = np.array(list2d)

In [11]:
[list2d[j][1:3] for j in range(2)]

[[2, 3], [5, 6]]

In [13]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [14]:
# En las listas la única operación que no da un error es la suma
lista1 = [1, 2, 3]

lista2 = [4, 5, 6]

lista1 + lista2

[1, 2, 3, 4, 5, 6]

In [15]:
# Los arreglos de numpy hacen elemnt-wise operations
arr1 = np.array(lista1)
arr2 = np.array(lista2)

print(arr1 + arr2)

print(arr1 - arr2)

print(arr1 * arr2)

print(arr1 / arr2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [16]:
# Lo mismo aplica para arreglos multidimensionales

arr1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

arr2 = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

arr1 + arr2

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [18]:
# Operaciones condicionales
arr = np.array(range(-5, 6))

print(arr)

print(arr < 0)

print(arr[arr < 0])

[-5 -4 -3 -2 -1  0  1  2  3  4  5]
[ True  True  True  True  True False False False False False False]
[-5 -4 -3 -2 -1]


In [19]:
# Broadcasting: podemos multiplicar un arreglo por una constante
# y se multiplica por cada uno de los elementos de la lista
arr = np.array(range(-5, 6))

arr * 2

array([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8,  10])

In [20]:
# Lo mismo pasa con arreglos multidimensionales
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

arr * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [21]:
arr2d = np.array([
    [1, 2, 3, 4],
    [1, 2, 3, 4],
    [1, 2, 3, 4]
])

arr1d = np.array([1, 2, 3, 4])

arr2d / arr1d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
# https://campus.datacamp.com/courses/practicing-coding-interview-questions-in-python/python-for-scientific-computing?ex=3
square = np.array([
    [ 1, 2, 3, 4, 5],
    [ 6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])

spiral = []

size = 5

for i in range(0, size):
    # Convert each part marked by any red arrow to a list
    spiral += list(square[i, i:size-i])
    # Convert each part marked by any green arrow to a list
    spiral += list(square[i+1:size-i, size-i-1])
    # Convert each part marked by any blue arrow to a list
    spiral += list(reversed(square[size-i-1, i+1:size-i-1]))
    # Convert each part marked by any magenta arrow to a list
    spiral += list(reversed(square[i+1:size-i-1, i]))
        
print([int(element) for element in spiral])

[1, 2, 3, 4, 5, 10, 15, 20, 25, 24, 23, 22, 16, 11, 6, 7, 8, 9, 14, 19, 18, 12, 13]
